### ISSUE TITLE
Hydra book by Naoto Hieda

### ISSUE THREAD

**Issue by flordefuego** [CreativeCodeBerlin/creative-coding-minilist#2]
https://hydra-book.naotohieda.com/#/ 

[Naoto Hieda](https://naotohieda.com/)

**Comment by micuat** [comment]
thanks! I added to the hackmd document so @SableRaf can publish later

**Comment by flordefuego** [comment]
Thank you and thank you so much for the article :)

**Comment by SableRaf** [comment]
Thanks! I published it :)
