### ISSUE TITLE
book suggestion - stranger games

### ISSUE THREAD

**Issue by poohlaga** [CreativeCodeBerlin/creative-coding-minilist#8]
https://www.amazon.com/Rise-Videogame-Zinesters-Drop-outs-Housewives/dp/1609803728/ref=sr_1_2?dchild=1&qid=1611610821&refinements=p_27%3AAnna+Anthropy&s=books&sr=1-2&text=Anna+Anthropy

**Comment by SableRaf** [comment]
Oooh! I want to read this 😊 Thanks for the suggestion!
